# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RGB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='aaaaaa', max_length=30)),
                ('R1', models.IntegerField(default=-999)),
                ('R1C', models.IntegerField(default=-999)),
                ('R2', models.IntegerField(default=-999)),
                ('R2C', models.IntegerField(default=-999)),
                ('G1', models.IntegerField(default=-999)),
                ('G1C', models.IntegerField(default=-999)),
                ('G2', models.IntegerField(default=-999)),
                ('G2C', models.IntegerField(default=-999)),
                ('B1', models.IntegerField(default=-999)),
                ('B1C', models.IntegerField(default=-999)),
                ('B2', models.IntegerField(default=-999)),
                ('B2C', models.IntegerField(default=-999)),
            ],
        ),
    ]
