# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgb',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
