# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-29 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgb',
            name='uid',
        ),
        migrations.AddField(
            model_name='rgb',
            name='Datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rgb',
            name='Statue1',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rgb',
            name='Statue2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rgb',
            name='Statue3',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rgb',
            name='Timestamp',
            field=models.IntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='rgb',
            name='Uid',
            field=models.CharField(default='123456789', max_length=30),
        ),
    ]
