# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_rgb_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgb',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
